create or replace table ` client_anonymisation_solution.anonymisation_country_param `
(
    type_customer     STRING,
    country           STRING,
    date_creation     DATE,
    retention_periods INT64 not null,
    retention_period_days INT64 not null
);


INSERT INTO ` client_anonymisation_solution.anonymisation_country_param ` (type_customer,
                                                                           country,
                                                                           date_creation,
                                                                           retention_periods,
                                                                           retention_period_days)
VALUES ("CLIENT", "FR", current_date(), 36, 1095),
       ("PROSPECT", "FR", current_date(), 36, 1095),
       ("CLIENT", "IT", current_date(), 36, 1095),
       ("PROSPECT", "IT", current_date(), 24, 730),
       ("CLIENT", "ES", current_date(), 36, 1095),
       ("PROSPECT", "ES", current_date(), 36, 1095),
       ("CLIENT", "PT", current_date(), 24, 730),
       ("PROSPECT", "PT", current_date(), 24, 730),
       ("CLIENT", "NL", current_date(), 36, 1095),
       ("PROSPECT", "NL", current_date(), 36, 1095),
       ("CLIENT", "RU", current_date(), 36, 1095),
       ("PROSPECT", "RU", current_date(), 36, 1095),
       ("CLIENT", "BE", current_date(), 36, 1095),
       ("PROSPECT", "BE", current_date(), 36, 1095),
       ("CLIENT", "PL", current_date(), 36, 1095),
       ("PROSPECT", "PL", current_date(), 36, 1095),
       ("CLIENT", "MT", current_date(), 36, 1095),
       ("PROSPECT", "MT", current_date(), 36, 1095),
       ("CLIENT", "CI", current_date(), 36, 1095),
       ("PROSPECT", "CI", current_date(), 36, 1095),
       ("CLIENT", "TN", current_date(), 36, 1095),
       ("PROSPECT", "TN", current_date(), 36, 1095),
       ("CLIENT", "MA", current_date(), 36, 1095),
       ("PROSPECT", "MA", current_date(), 36, 1095),
       ("CLIENT", "DZ", current_date(), 36, 1095),
       ("PROSPECT", "DZ", current_date(), 36, 1095),
       ("CLIENT", "SA", current_date(), 36, 1095),
       ("PROSPECT", "SA", current_date(), 36, 1095),
       ("CLIENT", "CD", current_date(), 36, 1095),
       ("PROSPECT", "CD", current_date(), 36, 1095),
       ("CLIENT", "SN", current_date(), 36, 1095),
       ("PROSPECT", "SN", current_date(), 36, 1095),
       ("CLIENT", "AE", current_date(), 36, 1095),
       ("PROSPECT", "AE", current_date(), 36, 1095),
       ("CLIENT", "BR", current_date(), 36, 1095),
       ("PROSPECT", "BR", current_date(), 36, 1095),
       ("CLIENT", "IN", current_date(), 36, 1095),
       ("PROSPECT", "IN", current_date(), 36, 1095),
       ("CLIENT", "others", current_date(), 36, 1095),
       ("PROSPECT", "others", current_date(), 36, 1095);