stages: # List of stages for jobs, and their order of execution
  - compile
  - test
  - release

dataform_compile: # This job runs in the build stage, which runs first.
  stage: compile
  image:
    name: dataformco/dataform:latest
    entrypoint: [ "" ]
  script:
    - dataform install
    - dataform compile

dataform_test:
  stage: test
  image:
    name: dataformco/dataform:latest
    entrypoint: [ "" ]
  script:
    - echo $GCP_SERVICE_KEY > .df-credentials.json
    - cat .df-credentials.json
    - dataform install
    - dataform test --vars=overrideRundate="2023-10-17"

#dataform_dry_run:
#  stage: release
#  image:
#    name: dataformco/dataform:latest
#    entrypoint: [""]
#  script:
#    - dataform install
#    - dataform run --dry-run

